[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h"]
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true

[[language]]
name = "cpp"
scope = "source.cpp"
file-types = ["cpp", "hpp", "h"]
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true
indent = { tab-width = 4, unit = " " }  # optional, adjust indent settings
